baseUrl: https://cubly.ru/
languageCode: ru-ru
defaultContentLanguage: ru
theme: terminal
paginate: 5

googleAnalytics: UA-44581121-8

copyright: Maxim Kurbatov
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # ["orange", "blue", "red", "green", "pink", "cubly"]
  themeColor: cubly
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 2
  # show selector to switch language
  showLanguageSelector: true
  # set theme to full screen width
  fullWidthTheme: false
  # center theme with default width
  centerTheme: true

languages:
  ru:
    languageName: ru
    title: "@maksimkurb"
    subtitle: Персональный сайт Максима Курбатова
    keywords: ''
    menuMore: Ссылки
    readMore: Читать далее
    readOtherPosts: Читать другие публикации

    params:
      logo:
        logoText: Cubly
        logoHomeLink: /

    menu:
      main:
      - identifier: posts
        name: Публикации
        url: /posts
        weight: 1

      #- identifier: about
      #  name: Обо мне
      #  url: /about
      #  weight: 2

      #- identifier: showcase
      #  name: Мои работы
      #  url: /showcase
      #  weight: 3

      - identifier: cv
        name: Резюме
        url: /cv
        weight: 4

      - identifier: rss
        name: RSS
        url: /posts/index.xml
        weight: 5

      - identifier: github
        name: GitHub
        url: https://github.com/maksimkurb/
        weight: 6

      - identifier: telegram
        name: Telegram
        url: https://t.me/maksimkurb
        weight: 7
  en:
    languageName: en
    title: "@maksimkurb"
    subtitle: Maxim Kurbatov's page
    keywords: ''
    menuMore: More
    readMore: Read more
    readOtherPosts: Read other posts

    params:
      logo:
        logoText: Cubly
        logoHomeLink: /


    menu:
      main:
      - identifier: posts
        name: Posts
        url: /posts
        weight: 1

      #- identifier: about
      #  name: About me
      #  url: /about
      #  weight: 2

      #- identifier: showcase
      #  name: Showcase
      #  url: /showcase
      #  weight: 3

      - identifier: cv
        name: CV
        url: /cv
        weight: 4

      - identifier: rss
        name: RSS
        url: /posts/index.xml
        weight: 5

      - identifier: github
        name: GitHub
        url: https://github.com/maksimkurb/
        weight: 6

      - identifier: telegram
        name: Telegram
        url: https://t.me/maksimkurb
        weight: 7